name: cell-factory-design-course
dependencies:
        - python==3.6
        - ipykernel
        - pandas==0.21.0
        - plotly==2.0.12
        - matplotlib==2.1.0
        - ipywidgets
        - pip:
          - cameo
          - escher==1.6.0
